EShop/Models/Groups.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EShop.Models
{
    public class Groups
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public int  ParentId { get; set; }
        public string ? Icon { get; set; }
        public string ? Page { get; set; }
        public DateTime CreateDate { get; set; } = DateTime.Now;
        public string? ShowCreateDate { get; set; }
        public DateTime? EditDate { get; set; }
        public string? ShowEditDate { get; set; }

    }
}

EShop/Areas/Admin/Controllers/GroupController.cs
using Microsoft.AspNetCore.Mvc;
 
namespace EShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    //[Authorize(Roles = "Admin")]
    public class GroupController : Controller
    {
        private readonly Models.Data.Repository.GroupRepository _repository;
        public GroupController(Models.Data.Repository.GroupRepository _repository)
        {
            this._repository = _repository;
        }
        public async Task<IActionResult> Index()
        {
            List<Models.Groups> Groups = await _repository.GroupList();
            if (Groups == null)
            {
                TempData["message"] = await Utilities.JSON.ToJson(new ViewModel.ErorVM() { State = false, Message = " لیست دسته بندی ها خالیست", AlertClass = "danger" });
                return View();
            }

            List<ViewModel.TreeViewVM> TreeViewNodes = new List<ViewModel.TreeViewVM>();
            foreach (var group in Groups)
            {
                TreeViewNodes.Add(new ViewModel.TreeViewVM()
                {
                    id = group.Id.ToString(),
                    parent = group.ParentId == 0 ? "#" : group.ParentId.ToString(),
                    text = group.Name.ToString()
                });
            }
            if( Utilities.JSON.ToJson(TreeViewNodes).Result !=null && Utilities.JSON.ToJson(TreeViewNodes).Result.Count() > 0)
            {
                ViewBag.JsonTreeData = await Utilities.JSON.ToJson(TreeViewNodes);
            }
            return View();
 
        }
        /// <summary>
        /// گروه جدید
        /// </summary>
        /// <param name="NewGroup"></param>
        /// <returns></returns>
        [HttpPost]
        public async Task<IActionResult> New(Models.Groups NewGroup)
		{
            List<Models.Groups> Groups = await _repository.GroupList();
            if (NewGroup == null)
            {
                TempData["message"] = await Utilities.JSON.ToJson(new ViewModel.ErorVM() { State = false, Message = "   گروه جدید خالیست", AlertClass = "danger" });
                return RedirectToAction("Index");
            }
            if (NewGroup.Name == null)
			{
                TempData["message"] = await Utilities.JSON.ToJson(new ViewModel.ErorVM() { State = false, Message = "  نام گروه جدید خالیست", AlertClass = "danger" });
                return RedirectToAction("Index");
            }
            if (NewGroup.ParentId == 0 && Groups.Count() > 0)
            {
                TempData["message"] = await Utilities.JSON.ToJson(new ViewModel.ErorVM() { State = false, Message = "  نام سرشاخه خالیست ", AlertClass = "danger" });
                return RedirectToAction("Index");
            }
            if (NewGroup.ParentId == 0 && Groups.Count() == 0)
            {// اضافه کردن یه ریشه (parentid = 0)
                NewGroup.ParentId = 0;
            }
            ViewModel.ErorVM Eror = await _repository.New(NewGroup);
            TempData["message"] = await Utilities.JSON.ToJson(Eror);
            return RedirectToAction("Index");
        }
     
    }
}

EShop/Areas/Admin/Views/Group/Index.cshtml
@model EShop.Models.Groups
@{
	ViewData["Title"] = "Index";
	Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@section Styles
{
<link rel="stylesheet" href="~/Plugin/Jstree/jstree.css" />
}
		
<div class="container-fluid">
	<div id="mainDash" class="main-body-content">
		@if (TempData["message"] != null)
		{
			var eror = await Utilities.JSON.ToObjet<ViewModel.ErorVM>(TempData["message"].ToString());
			<div class="container pb-3">
				<div class="col-6 mx-auto alert alert-@eror.AlertClass text-center text-secondary" id="eror" role="alert">
					@eror.Message

				</div>
			</div>
		}
		<div class="main-header">
			<div class="inner">
				<div class="title">
					<i class="fi-rr-apps-add"></i>
					<h1>دسته‌بندی ها</h1>
				</div>
			</div>
		</div>

		<div class="main-inner">
			<div class="category-grid-layout">
				<div class="row">
					<div class="col-lg-7 col-md-8 col-sm-12">
						<div class="tabs-dashboards">
							<nav>
								<div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
									<button class="nav-link  active" id="nav-allgroup-tab" data-bs-toggle="tab" data-bs-target="#nav-allgroup" type="button" role="tab" aria-controls="nav-allBook" aria-selected="true">
										<span class="icon"><i class="fi fi-rr-list  fs-5"></i></span>
										<span class="tab-name"> لیست گروه ها </span>
									</button>
								</div>
							</nav>
							<div class="tab-content" id="nav-tabContent">
								<div class="tab-pane fade show active " id="nav-allgroup" role="tabpanel" aria-labelledby="nav-allBook-tab">
									<div class="category-forms">
										<div id="jstree"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-5 col-md-4 col-sm-12">
						<div class="tabs-dashboards">
							<nav>
								<div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
									<button class="nav-link  active" id="nav-addgroup-tab" data-bs-toggle="tab" data-bs-target="#nav-addgroup" type="button" role="tab" aria-controls="nav-allBook" aria-selected="true">
										<span class="icon"><i class="fi fi-rr-add text-success fs-5"></i></span>
										<span class="tab-name"> گروه جدید </span>
									</button>
									<button class="nav-link" id="nav-editgroup-tab" data-bs-toggle="tab" data-bs-target="#nav-editgroup" type="button" role="tab" aria-controls="nav-bookhidden" aria-selected="true">
										<span class="icon"><i class="fi fi-rr-edit text-info fs-5"></i></span>
										<span class="tab-name"> ویرایش  </span>
									</button>
									<button class="nav-link" id="nav-deletegroup-tab" data-bs-toggle="tab" data-bs-target="#nav-deletegroup" type="button" role="tab" aria-controls="nav-discount" aria-selected="true">
										<span class="icon"><i class="fi fi-rr-cross text-danger fs-5"></i></span>
										<span class="tab-name"> حذف </span>
									</button>
								</div>
							</nav>
							<div class="tab-content" id="nav-tabContent">
								<div class="tab-pane fade show active" id="nav-addgroup" role="tabpanel" aria-labelledby="nav-allBook-tab">
									@using(Html.BeginForm("New","Group",FormMethod.Post))
									{
									   <input type="hidden"  id="parentid" name="ParentId">
										<div class="category-forms">
											<div class="row">
												<div class="col-lg-12">
													<div class="inputgroup nopadding">
														<label> نام گروه </label>
														<input type="text" class="input" name="Name" placeholder="نام گروه" required="">
													</div>
												</div>
												<div class="col-lg-12">
													<div class="inputgroup nopadding">
														<label>  نام سرشاخه </label>
														<input type="text" class="input" id="parentname"  placeholder="نام سرشاخه" required="" disabled>
													</div>
												</div>
												<div class="col-lg-12">
													<div class="inputgroup nopadding">
														<label>  آدرس صفحه </label>
														<input type="text" class="input" name="Page" placeholder="آدرس صفحه">
													</div>
												</div>
												<div class="col-lg-12">
													<div class="inputgroup nopadding">
														<label>آیکن</label>
														<input type="text" class="input" name="Icon" placeholder="آیکن" >
													</div>
												</div>
												<div class="col-lg-12">
													<div class="button-group">
														<button type="submit" class="btn btn-primary">اضافه کردن</button>
													</div>
												</div>
											</div>
										</div>
								      }
								</div>
								<div class="tab-pane fade" id="nav-editgroup" role="tabpanel" aria-labelledby="nav-bookhidden-tab">
									عدم نمایش
								</div>
								<div class="tab-pane fade" id="nav-deletegroup" role="tabpanel" aria-labelledby="nav-discount-tab">
									تخفیف‌ها
								</div>

							</div>
						</div>

					</div>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts
{
	<script src="~/Plugin/Jstree/jstree.js"></script>

<script>
	$(document).ready(function () {
		$('#jstree').jstree({
		"core": {
				'multiple': false,
			'check_callback': true,
				'themes': {
					'name': 'proton',
					'responsive': true,
					"icons": false,
				},
			"data": @Html.Raw(ViewBag.JsonTreeData),
		},

			'plugins': ["wholerow", "checkbox"],
		});
		$("#jstree").on('changed.jstree', function (e, data) {
			var i, j;
			var selectedItems = [];
			for (i = 0, j = data.selected.length; i < j; i++) {
				//Fetch the Id.
				var id = data.selected[i];
				//Remove the ParentId.
				if (id.indexOf('-') != -1) {
					id = id.split("-")[1];
				}
				//Add the Node to the JSON Array.
				selectedItems.push({
					text: data.instance.get_node(data.selected[i]).text,
					id: id,
					parent: data.node.parents[0]
				});
			}
			//Serialize the JSON Array and save in HiddenField.
		    $('#selectedItems').val(JSON.stringify(selectedItems));
			$('#parentid').prop('readonly', true); // برای اینکه بتوانیم با استفاده از جی کویری مقدار اینپوت را به مدل بایند کنیم
            if(selectedItems != null)
			{
		    var selected = selectedItems[0];
			if (selected != null) {
				$('#parentname').val(selected.text);
				$('#parentid').val(selected.id);
			}
			else {
				$('#parentname').val("");
				$('#parentid').val("");
			}

			}
		});
 	});
</script>
}